config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
  	resources :reviews
  	resources :notifies
  end
  
  resources :carts
  
  root 'products#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :product
	validates :quantity, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/notify.rb
class Notify < ApplicationRecord
  belongs_to :product


end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :reviews , dependent: :destroy		
	has_many :carts, dependent: :destroy
	has_many :notifies
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :carts, dependent: :destroy
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_email
  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :find_cart, only: [:show, :edit, :update, :destroy]

    def create
        @cart = Cart.new(cart_params)
        @cart.product_id = session[:product_id]
        @cart.user_id = current_user.id  
        @cart.save
        redirect_to carts_path
    end

    def index
        @carts = Cart.where(user_id: current_user.id)
    end

    def show
    end

    def destroy
        @cart.destroy
        redirect_to carts_path
    end

    private

    def cart_params
      params.require(:cart).permit!
    end 

    def find_cart
        @cart = Cart.find(params[:id])
    end

end

app/controllers/notifies_controller.rb
class NotifiesController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @notify = @product.notifies.new
    @notify.user_id = current_user.id
    @notify.save
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    include NotifiesHelper
    before_action :find_product, only:[:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def index
        if params[:category].blank?
         @product = Product.all.order("created_at DESC")

        else
         category_id = Category.find_by(name: params[:category]).id
         @product=Product.where(category_id: category_id).order("created_at DESC")
        end
    end

    def new
        @product = Product.new
        @categories = Category.all.map { |c| [c.name, c.id] }
    end

    def create
        @product = Product.create(product_params)
        @product.category_id = params[:category_id] 
        if @product.save
            redirect_to root_path
        else
        render 'new' 
        end
    end

    def show
      session[:product_id] = @product.id 
        if @product.reviews.blank?
            @average_review = 0
        else
            @average_review =   @product.reviews.average(:rating).round(2)
        end
    end

    def edit
        @categories = Category.all.map { |c| [c.name, c.id] }
          
    end


    def update
      if @product.update(product_params)
        if @product.status == true && @product.notifies
          users = []
          users = Notify.where(product_id: @product.id)
          prod_id = @product.id
          notify_mailer(users,prod_id)
        end
      redirect_to root_path (@product)
      else
        render 'edit'
      end
    end

    def destroy
        @product.destroy
        redirect_to root_path
    end

    private

    def product_params
        params.require(:product).permit(:name, :price, :status, :image, :category_id)
    end

    def find_product
        @product = Product.find(params[:id])
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_product
	before_action :find_review, only: [:edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
	@product= Product.find(params[:product_id])
    @review= @product.reviews.create(review_params)
    @review.user_id = current_user.id
      if @review.save
        redirect_to product_path(@product)
      else
        render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to product_path(@product)
		else
			render 'edit'
		end
	end

	def show
		
	end

	def destroy
		  @review.destroy
		  redirect_to product_path(@product)
	end

	private
	def review_params
		params.require(:review).permit(:rating, :comment)
	end 

	def find_product
		@product = Product.find(params[:product_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper

    def total(quantity,price)
      c = quantity*price
      return c 
    end

end

app/helpers/notifies_helper.rb
module NotifiesHelper

  def notify_mailer(users,prod_id)
    @product = Product.find_by(id: prod_id)
    users.each do|user|
      @user = User.find_by(id: user.user_id)
      NotifyMailer.notify_email(@user, @product).deliver_now 
    end
  end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/_show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Please fill the quantity of product</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>quantity</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

</body>
</html>

app/views/carts/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12", style="margin-right: 110px;">
            <h2 style="text-align: center;"><u><i> Your Cart</i></u></h2>
            
            
            <div class = "row ">
              <div class="col-md-2 text-left">
                  <h3><i>Image</i></h3>   
              </div>                
            
                <div class="col-md-2 text-left">
                    <h3><i>name</i></h3>    
                </div>                
            
                <div class="col-md-2 text-left">
                    <h3><i>Price</i></h3>    
                </div>
                
                <div class="col-md-2 text-left">
                    <h3><i>Quantity</i></h3>    
                </div>                
                
                <div class="col-md-2 text-left">
                  <h3><i>Total</i></h3>    
                </div>
            </div>
            <hr>
            <% a=0 %>          
            <% @carts.each do |cart| %>
                <div class = "row">
                    
                    <div class="col-md-2">
                        
                        <div class="cart-card">
                            <a href="<%= product_path(cart.product.try(:id))%>">
                                <img alt="", src="<%=cart.product.try(:image_url) %> " class="cart-img">
                            </a>
                        </div>    
                    
                    </div>
                    
                    <div class = "col-md-2 cart-margin">
                      <h3><%=cart.product.try(:name)%></h3>    
                    </div>
                    
                    <div class = "col-md-2 cart-margin">
                      <h3><%=cart.product.try(:price)%></h3>    
                    </div>
                    
                    <div class="col-md-2 cart-margin">
                      <h3><%=cart.try(:quantity)%></h3>
                    </div>

                    <div class="col-md-2 cart-margin">

                    <h3><%= total(cart.try(:quantity),cart.product.try(:price))%></h3>
                      <% a = a+(total(cart.try(:quantity),cart.product.try(:price)))%>
                    </div>
                    <div class="col-md-2 cart-btn-margin">
                      <%= link_to "Remove", cart_path(cart.id), method: :delete , class: "btn btn-danger" %> 
                    </div>
                   
                </div>
                
              <% end %>
              <div class="col-md-2 text-right", style="text-align: right; color: blue;">
                <h3><i>Grandtotal<br><%= a%></i></h3>    
              </div>
        </div>
        
    </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
    <div class="container">

      <div class="navbar-header">
        <%= link_to "Product Store", root_path, class: "navbar-brand" %>
      </div>
    
      <ul class="nav navbar-nav">
        <li><%=link_to "sign_up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>            
            <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">

                 <%= link_to category.name, products_path(category: category.name), class: "link" %>
                </li>
                <% end %>

            </ul>
          </li>
        	 
        <% if user_signed_in? %>
         	<li><%= link_to "Add Product", new_product_path %></li>
        <% end %>
      </ul>
    </div>  


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

		<div class="container">
    	<%= yield %>
		</div>

  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
	<%=f.input :name, label: 'Product name' %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category")%>
	<%= f.file_field :image %>
	<%=f.input :price %>
	<%= f.input :status %>
	<%= f.button :submit , label: 'Save product', class: "btn-custom2" %>
<% end %>

app/views/products/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-book-form">

<h1> Edit product </h1>
<%= simple_form_for @product do |f| %>
	<%=f.input :name, label: 'Product name' %>
	<%= f.select :category_id , @categories %>
	<%= f.file_field :image %>
	<%=f.input :price %>
	<%= f.input :status %>
	<%= f.button :submit , label: 'Save product', class: "btn-custom2" %>
<% end %>

app/views/products/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

  <% if @product.all.count == 0 %>
     <h1>There are no products currently in this category</h1>
  <% else %>
  <div class="row">
		<% @product.each do |product| %>
			<div class="col-md-3">
					<a href="/products/<%= product.id %>">
					<%= image_tag product.image.url,  class: "book"%>
					</a>
			</div>
	<% end %>

	</div>

	<%end%>

app/views/products/new.html.erb
<h1> New Product </h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-4">
  <h2><%= image_tag @product.image.url%></h2>
  </div>

  

  <div class="col-md-8">
    <div class="book-info", style="padding: 3.5em 1.25em;">

          <h2 class="book-title"><%= @product.name %> </h2>
          <h3 class="book-author"> Price : <%= @product.price %></h3>
          <h2 class="average-rating">Average Rating</h2>
          <div class="average-review-rating" data-score=<%= @average_review %>></div>
          <span class="number-of-reviews">Based on <%= @product.reviews.count %> reviews </span>
          <p class="book-desc"
          <% if @product.status %>
            <h4 style="text-align: right; color: blue;"> Product is available </h4>
          <% else %>
            <h4 style="text-align: right; color: red;"> Out of stock </h4>
              <br><%= link_to "Notify me",  product_notifies_url(@product), method: :post, class: "btn btn-primary" %>
          <% end %> </p>
          <div>
            <p class="dropdown">
              <% if @product.status == true%>
                <%= form_for :cart, url: carts_path, method: :post do |form| %>
                  <%= form.select :quantity, [1,2,3,4,5], prompt: "Select Quantity", class: "btn-custom"%> <br>
                    <ul class="nav navbar-nav navbar-right">
                      <%=form.submit "Add to cart", class: "btn-custom" %>
                <% end %>
              <%end%>
                  
            </p>

          </ul> 
          </div>
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="reviews">

          <h1>Reviews</h1>
          <%= render @product.reviews %>

          <div>

            <%= link_to "Add Review", new_product_review_path(@product),class: "btn-custom" %>

          </div>

        </div>

      </div>

    </div>

    <div class="links btn-group">

      <%= link_to "Back", root_path, class: "btn btn-custom" %> 

              <%= link_to "Edit", edit_product_path(@product), class: "btn btn-custom" %>
              <%= link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-custom" %>
         
     </div> 

     <script> // for ratings
       $('.review-rating').raty({
         readOnly: true,
         score: function() {
           return $(this).attr('data-score');
         },
         path: '/assets/'
       });
     </script>

     <script> //for average ratings
       $('.average-review-rating').raty({
         readOnly: true,
         score: function() {
           return $(this).attr('data-score');
         },
         path: '/assets/'
       });
     </script>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@product, @product.reviews.build] )do |f| %>
	<div id="rating-form">
	  <label> Rating </label>
	</div>

	<%= f.input :comment %>
	<%= f.button :submit ,label: 'Add review', class: "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="reviews">

<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"><%= review.comment %></p>

<% if user_signed_in? %>

  <% if review.user_id == current_user.id %>

    <div class="links btn-group">

  	  <%= link_to "Edit", edit_product_review_path(review.product, review),class: "btn btn-custom" %>

  	  <%=link_to "Delete", product_review_path(review.product, review), method: :delete, data:{confirm: "Are you sure"}, class: "btn btn-custom" %>
    </div>

  <% end %>
<% end %>

</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">

    <h1>Edit Review </h1>
    <%= simple_form_for ([@product, @review] ) do |f| %>
    	<div id="rating-form">
    	  <label> Rating </label>
    	</div>
    	<%= f.input :comment %>
    	<%= f.button :submit, class: "btn-custom2" %>

    <% end %>
  </div>
</div>
<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1> New Review </h1>
<%= render 'form' %>